### ISSUE TITLE
issue with plotting

### ISSUE THREAD

**Issue by ThomasGro** [albertopessia/drda#8]
Thank you so much for providing this nice package. 

I have some issues with plotting.

- I generated a 4 parametric fit of this data x:

      Compound	Cell	conc	GI	relGI
      drug1	MDAMB436	1,00E-09	94,12125	0,9412125
      drug1	MDAMB436	5,00E-09	89,76748	0,8976748
      drug1	MDAMB436	1,67E-08	79,58089	0,7958089
      drug1	MDAMB436	5,00E-08	72,59264	0,7259264
      drug1	MDAMB436	1,67E-07	67,35769	0,6735769
      drug1	MDAMB436	5,00E-07	53,64598	0,5364598
      drug1	MDAMB436	1,67E-06	33,58508	0,3358508
      drug1	MDAMB436	5,00E-06	30,55685	0,3055685
      drug1	MDAMB436	5,00E-05	15,06649	0,1506649
      
  > lb <- c(1, -1, -Inf, -Inf)
  > ub <- c(1, Inf, Inf, Inf)
  > fit=drda::drda(x$rel.gi ~ log10(x$conc),
                   mean_function = "logistic4",
                   lower_bound = lb,
                   upper_bound = ub))

- summary of the fit:
        > summary(fit)
        
        Call: drda::drda(formula = x$rel.gi ~ log10(x$conc), mean_function = "logistic4", 
            lower_bound = lb, upper_bound = ub)
        
        Pearson Residuals:
            Min       1Q   Median       3Q      Max  
        -1.6240  -0.4998   0.1265   0.4788   1.2993  
        
        Parameters:
                          Estimate Std. Error Lower .95 Upper .95
        Maximum            1.00000         NA        NA        NA
        Height            -0.96278    0.07109  -1.10211    -0.823
        Growth rate        1.02122    0.11853   0.78890     1.254
        Midpoint at       -6.31416    0.19131  -6.68913    -5.939
        Residual std err.  0.03325    0.01108   0.01153     0.055
        
        Residual standard error on 6 degrees of freedom
        
        Log-likelihood: 19.687
        AIC: -31.374
        BIC: -30.585
        
        Optimization algorithm converged in 289 iterations

- plotting fails with error:

    > plot(fit)
    Error in crossprod(G[i, ], V) : non-conformable argument
    
    8.crossprod(G[i, ], V) at curve_variance.R#31
    7.tcrossprod(crossprod(G[i, ], V), G[i, ]) at curve_variance.R#31
    6.curve_variance.drda(x, xx) at S3.R#50
    5.curve_variance(x, xx) at plot.R#547
    4.plot_params.logistic(x, dotargs[["base"]], dotargs[["xlim"]],
    dotargs[["ylim"]]) at S3.R#62
    3.plot_params(x, dotargs[["base"]], dotargs[["xlim"]], dotargs[["ylim"]]) at plot.R#99
    2.plot.drda(fit)
    1.plot(fit)

Please let me know if you need more details.

**Comment by albertopessia** [comment]
Hi @ThomasGro, thank you for your report.
The bug has been fixed in the devel branch [ff65254](https://github.com/albertopessia/drda/commit/ff65254d61a46f0bf3c3e4f0628df1b31ac7e642).
